# Site settings
title: Mustafa Writes!
email: 
description: "My Experience as a Computer Science Engineering Student."
baseurl: ""
url: "https://mustafa1310.github.io/MyBlogs/"
github_username:  Mustafa1310
# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
